### ISSUE TITLE
'BroadcastOutput' object has no attribute 'start'

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/NCSLab#12]
Traceback (most recent call last):
  File "/home/hyx020222/pistreaming/server.py", line 181, in <module>
    main()
  File "/home/hyx020222/pistreaming/server.py", line 153, in main
    camera.start_recording(output, 'yuv')
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1760, in start_recording
    self.start_encoder(encoder, output, pts=pts, quality=quality, name=name)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1700, in start_encoder
    _encoder.start(quality=quality)
    ^^^^^^^^^^^^^^
AttributeError: 'BroadcastOutput' object has no attribute 'start'

**Comment by HuaYuXiao** [comment]
replace `picamera` with `picamera2`
