### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by HuaYuXiao** [HuaYuXiao/NCSLab#21]
```
hyx020222@hyx020222-ThinkBook-14:~$ npx vite

  VITE v5.3.1  ready in 532 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
node:internal/fs/watchers:247
    const error = new UVException({
                  ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/hyx020222/.gazebo/models/gazebo-models/r2_description/meshes'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43324:17)
    at setFsWatchListener (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43371:15)
    at NodeFsHandler._watchWithNodeFs (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43526:14)
    at NodeFsHandler._handleDir (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43762:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43812:16)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:45025:10)
    at NodeFsHandler._addToNodeFs (file:///home/hyx020222/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:43840:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/hyx020222/.gazebo/models/gazebo-models/r2_description/meshes',
  filename: '/home/hyx020222/.gazebo/models/gazebo-models/r2_description/meshes'
}

Node.js v20.14.0
```

**Comment by HuaYuXiao** [comment]
你遇到的错误是 `ENOSPC`，这表示系统达到了文件监视器的数量限制。在Linux系统中，每个用户都有一个文件监视器数量的限制，当超过这个限制时，就会抛出这个错误。

这个问题通常发生在使用Node.js开发工具时，比如Vite。解决这个问题的方法之一是增加文件监视器的数量限制。你可以通过以下步骤来解决这个问题：

1. 打开终端。
2. 检查当前的文件监视器限制，使用命令：
   ```bash
   cat /proc/sys/fs/inotify/watchers
   ```
3. 如果需要，增加文件监视器的数量限制，使用命令：
   ```bash
   sudo sysctl fs.inotify.max_user_watches=524288
   ```
   这会将限制设置为524288，你可以根据需要调整这个值。

4. 为了使这个更改持久化，你可以编辑 `/etc/sysctl.conf` 文件，并添加或修改以下行：
   ```bash
   fs.inotify.max_user_watches=524288
   ```
   然后保存并关闭文件。

5. 应用更改，使用命令：
   ```bash
   sudo sysctl -p
   ```

6. 重新启动你的Vite服务器，再次运行 `npx vite`。

请注意，这些更改可能需要管理员权限，所以使用 `sudo` 命令时可能需要输入密码。如果你不确定如何操作，或者担心可能会影响系统稳定性，建议在进行更改前咨询有经验的系统管理员。

**Comment by HuaYuXiao** [comment]
run `npx vite` under `~/NCSLab` rather than `~/`
